package com.grupo2.sistemadegestionveterinaria.vista;

import com.grupo2.sistemadegestionveterinaria.modelo.ModeloCliente;
import com.grupo2.sistemadegestionveterinaria.data.DbDAOMod1; // Ajusta según tu estructura
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Galo Izquierdo
 */
public class DlgSeleccionarCliente extends javax.swing.JDialog {

    private ModeloCliente clienteSeleccionado = null;
    private final DbDAOMod1 dao = new DbDAOMod1();

    public DlgSeleccionarCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // Define las columnas deseadas y bloquea la edición de celdas
        tblClientes.setModel(new DefaultTableModel(
                new Object[][]{},
                new String[]{"Cédula", "Nombres"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Evita que el usuario edite los datos en la tabla
            }
        });
        setLocationRelativeTo(null);
        cargarTabla();
    }

    private void cargarTabla() {
        DefaultTableModel model = (DefaultTableModel) tblClientes.getModel();
        model.setRowCount(0); // Limpia la tabla primero

        try {
            List<ModeloCliente> clientes = dao.listarClientes();
            for (ModeloCliente c : clientes) {
                model.addRow(new Object[]{c.getCedula(), c.getNombres()});
            }
        }
        catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar clientes: " + e.getMessage());
            e.printStackTrace();
        }
    }

    public ModeloCliente getClienteSeleccionado() {
        return clienteSeleccionado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    tblClientes = new javax.swing.JTable();
    btnok = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    tblClientes.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane1.setViewportView(tblClientes);

    btnok.setText("Aceptar");
    btnok.setToolTipText("");
    btnok.setName("btnok"); // NOI18N
    btnok.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnokActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(btnok)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(19, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(8, Short.MAX_VALUE)
        .addComponent(btnok)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void btnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokActionPerformed
        int fila = tblClientes.getSelectedRow();
        if (fila != -1) {
            String cedula = (String) tblClientes.getValueAt(fila, 0);
            try {
                clienteSeleccionado = dao.buscarCliente(cedula);
            }
            catch (Exception e) {
                e.printStackTrace();
            }
            dispose();
        }
    }//GEN-LAST:event_btnokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgSeleccionarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgSeleccionarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgSeleccionarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgSeleccionarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgSeleccionarCliente dialog = new DlgSeleccionarCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        dialog.dispose();
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnok;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable tblClientes;
  // End of variables declaration//GEN-END:variables
}
