/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.grupo2.sistemadegestionveterinaria.vista;

import com.grupo2.sistemadegestionveterinaria.controlador.ControladorClienteMascota;
import com.grupo2.sistemadegestionveterinaria.modelo.ModeloCliente;
import com.grupo2.sistemadegestionveterinaria.modelo.ModeloMascota;
import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Galo Izquierdo
 */
public class FrmMascota extends javax.swing.JFrame {

  private ModeloCliente clienteActual = null;
  private DefaultTableModel modelo;

  /**
   * Creates new form FrmMascota
   */
  public FrmMascota() {
    setSize(750, 500);
    setLocationRelativeTo(null);
    setDefaultCloseOperation(EXIT_ON_CLOSE);

    initComponents();
    modelo = new DefaultTableModel(
            new Object[]{"ID", "Nombre", "Raza", "Especie"}, 0
    ) {
      public boolean isCellEditable(int row, int col) {
        return col != 0; // ID no editable
      }
    };
    tabla.setModel(modelo);
    // ocultar columna ID
    tabla.getColumnModel().getColumn(0).setMinWidth(0);
    tabla.getColumnModel().getColumn(0).setMaxWidth(0);
    //configurarValidaciones();
  }

  private void limpiarTabla() {
    modelo.setRowCount(0);
  }

  private void bloquearUI(boolean estado) {
    btnGuardar.setEnabled(!estado);
    btnAgregar.setEnabled(!estado);
  }

  private ModeloCliente getCliente() {

    if (clienteActual == null) {
      clienteActual = new ModeloCliente();
    }

    clienteActual.setCedula(txtCedula.getText());
    clienteActual.setNombres(txtNombre.getText());
    clienteActual.setTelefono(txtTelefono.getText());

    return clienteActual;
  }

  private List<ModeloMascota> getMascotasTabla() {

    List<ModeloMascota> lista = new ArrayList<>();

    for (int i = 0; i < modelo.getRowCount(); i++) {

      ModeloMascota m = new ModeloMascota();

      m.setId(Integer.parseInt(modelo.getValueAt(i, 0).toString()));
      m.setNombre(modelo.getValueAt(i, 1).toString());
      m.setRaza(modelo.getValueAt(i, 2).toString());
      m.setEspecie(modelo.getValueAt(i, 3).toString());

      lista.add(m);
    }

    return lista;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pnCli = new javax.swing.JPanel();
    lbced = new javax.swing.JLabel();
    lbnom = new javax.swing.JLabel();
    lbtel = new javax.swing.JLabel();
    txtCedula = new javax.swing.JTextField();
    txtTelefono = new javax.swing.JTextField();
    txtNombre = new javax.swing.JTextField();
    btnBuscar = new javax.swing.JButton();
    lbEstado = new javax.swing.JLabel();
    pnMasc = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    btnAgregar = new javax.swing.JButton();
    btnEliminar = new javax.swing.JButton();
    cbEspecie = new javax.swing.JComboBox<>();
    jLabel3 = new javax.swing.JLabel();
    txtMascota = new javax.swing.JTextField();
    txtRaza = new javax.swing.JTextField();
    scroll = new javax.swing.JScrollPane();
    jScrollPane1 = new javax.swing.JScrollPane();
    tabla = new javax.swing.JTable();
    btnGuardar = new javax.swing.JButton();
    btnSalir = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Registro de Mascotas/Clientes");
    setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    setResizable(false);

    pnCli.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

    lbced.setText("Cédula:");

    lbnom.setText("Nombres:");

    lbtel.setText("Teléfono:");

    txtCedula.setToolTipText("");
    txtCedula.setName(""); // NOI18N

    txtTelefono.setName(""); // NOI18N

    txtNombre.setName(""); // NOI18N

    btnBuscar.setText("Buscar");
    btnBuscar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBuscarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout pnCliLayout = new javax.swing.GroupLayout(pnCli);
    pnCli.setLayout(pnCliLayout);
    pnCliLayout.setHorizontalGroup(
      pnCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnCliLayout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addGroup(pnCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lbced)
          .addComponent(lbnom))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(pnCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(pnCliLayout.createSequentialGroup()
            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(87, 87, 87)
            .addComponent(lbtel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(57, 57, 57)
        .addGroup(pnCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(lbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnBuscar))
        .addContainerGap(22, Short.MAX_VALUE))
    );
    pnCliLayout.setVerticalGroup(
      pnCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnCliLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(pnCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(lbtel)
            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnBuscar))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(lbced)
            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGroup(pnCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(pnCliLayout.createSequentialGroup()
            .addGap(14, 14, 14)
            .addGroup(pnCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(lbnom)))
          .addGroup(pnCliLayout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addComponent(lbEstado)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pnMasc.setBorder(javax.swing.BorderFactory.createTitledBorder("Mascotas"));

    jLabel1.setText("Nombre:");

    jLabel2.setText("Raza:");

    btnAgregar.setText("Agregar");
    btnAgregar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAgregarActionPerformed(evt);
      }
    });

    btnEliminar.setText("Eliminar");
    btnEliminar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEliminarActionPerformed(evt);
      }
    });

    cbEspecie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perro", "Gato", "Hamster", "Loro", "Conejo", "Otros" }));

    jLabel3.setText("Especie");

    tabla.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane1.setViewportView(tabla);

    scroll.setViewportView(jScrollPane1);

    javax.swing.GroupLayout pnMascLayout = new javax.swing.GroupLayout(pnMasc);
    pnMasc.setLayout(pnMascLayout);
    pnMascLayout.setHorizontalGroup(
      pnMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMascLayout.createSequentialGroup()
        .addGroup(pnMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(pnMascLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(scroll))
          .addGroup(pnMascLayout.createSequentialGroup()
            .addGap(27, 27, 27)
            .addGroup(pnMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel1)
              .addComponent(jLabel2))
            .addGap(27, 27, 27)
            .addGroup(pnMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(txtMascota, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
              .addComponent(txtRaza))
            .addGap(18, 18, 18)
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(cbEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
            .addGroup(pnMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(btnEliminar)
              .addComponent(btnAgregar))))
        .addGap(27, 27, 27))
    );
    pnMascLayout.setVerticalGroup(
      pnMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnMascLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1)
          .addGroup(pnMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(jLabel3)
            .addComponent(txtMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(cbEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnAgregar)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(txtRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnEliminar))
        .addGap(18, 18, 18)
        .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(19, Short.MAX_VALUE))
    );

    btnGuardar.setText("Guardar");
    btnGuardar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnGuardarActionPerformed(evt);
      }
    });

    btnSalir.setText("Salir");
    btnSalir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSalirActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnGuardar)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnSalir)
        .addGap(24, 24, 24))
      .addGroup(layout.createSequentialGroup()
        .addGap(15, 15, 15)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(pnMasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(pnCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(0, 18, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(32, 32, 32)
        .addComponent(pnCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(32, 32, 32)
        .addComponent(pnMasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(121, 121, 121)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnSalir)
          .addComponent(btnGuardar))
        .addGap(0, 15, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
    try {
      ControladorClienteMascota ctrl = new ControladorClienteMascota();

      List<ModeloMascota> lista = new ArrayList<>();

      clienteActual = ctrl.buscar(txtCedula.getText(), lista);

      modelo.setRowCount(0);

      if (clienteActual != null) {

        txtNombre.setText(clienteActual.getNombres());
        txtTelefono.setText(clienteActual.getTelefono());

        for (ModeloMascota m : lista) {
          modelo.addRow(new Object[]{
            m.getId(),
            m.getNombre(),
            m.getRaza(),
            m.getEspecie()
          });
        }

        lbEstado.setText("Cliente cargado");

      } else {
        clienteActual = new ModeloCliente();
        clienteActual.setCedula(txtCedula.getText());

        limpiarTabla();
        lbEstado.setText("Nuevo cliente");
      }

    } catch (Exception e) {
      JOptionPane.showMessageDialog(this, e.getMessage());
    }
  }//GEN-LAST:event_btnBuscarActionPerformed

  private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

    if (txtMascota.getText().isEmpty() || txtRaza.getText().isEmpty()) {
      JOptionPane.showMessageDialog(this, "Complete datos mascota");
      return;
    }

    modelo.addRow(new Object[]{
      0,
      txtMascota.getText(),
      txtRaza.getText(),
      cbEspecie.getSelectedItem().toString()
    });

    txtMascota.setText("");
    txtRaza.setText("");
  }//GEN-LAST:event_btnAgregarActionPerformed

  private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    int fila = tabla.getSelectedRow();
    if (fila >= 0) {
      modelo.removeRow(fila);
    }
  }//GEN-LAST:event_btnEliminarActionPerformed

  private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    try {
      bloquearUI(true);

      ModeloCliente c = getCliente();
      List<ModeloMascota> lista = getMascotasTabla();

      ControladorClienteMascota ctrl = new ControladorClienteMascota();
      ctrl.guardar(c, lista);

      lbEstado.setText("Guardado OK");

    } catch (Exception e) {
      JOptionPane.showMessageDialog(this, e.getMessage());
    } finally {
      bloquearUI(false);
    }
  }//GEN-LAST:event_btnGuardarActionPerformed

  private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
    System.exit(0);
  }//GEN-LAST:event_btnSalirActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FrmMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FrmMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FrmMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FrmMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new FrmMascota().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAgregar;
  private javax.swing.JButton btnBuscar;
  private javax.swing.JButton btnEliminar;
  private javax.swing.JButton btnGuardar;
  private javax.swing.JButton btnSalir;
  private javax.swing.JComboBox<String> cbEspecie;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lbEstado;
  private javax.swing.JLabel lbced;
  private javax.swing.JLabel lbnom;
  private javax.swing.JLabel lbtel;
  private javax.swing.JPanel pnCli;
  private javax.swing.JPanel pnMasc;
  private javax.swing.JScrollPane scroll;
  private javax.swing.JTable tabla;
  private javax.swing.JTextField txtCedula;
  private javax.swing.JTextField txtMascota;
  private javax.swing.JTextField txtNombre;
  private javax.swing.JTextField txtRaza;
  private javax.swing.JTextField txtTelefono;
  // End of variables declaration//GEN-END:variables
}
